export const SET_RECHARGE_LOADING = "SET_RECHARGE_LOADING"
export const FETCH_RECHARGES = "FETCH_RECHARGES"
export const FETCH_RECHARGES_BY_ID = "FETCH_RECHARGES_BY_ID"

export const FETCH_TRANSACTIONS = "FETCH_TRANSACTIONS"
export const FETCH_TRANSACTIONS_BY_ID = "FETCH_TRANSACTIONS_BY_ID"

// ===================== NEW ACTION =====================
export const SET_SIZE_PER_PAGE_TRANSACTIONS = "SET_SIZE_PER_PAGE_TRANSACTIONS"
export const SET_PAGE_TRANSACTIONS = "SET_PAGE_TRANSACTIONS"
export const SET_SEARCH_TRANSACTIONS = "SET_SEARCH_TRANSACTIONS"
export const SET_SORT_FIELD_TRANSACTIONS = "SET_SORT_FIELD_TRANSACTIONS"
export const SET_SORT_ORDER_TRANSACTIONS = "SET_SORT_ORDER_TRANSACTIONS"
