export const SET_RECHARGE_LOADING = 'SET_RECHARGE_LOADING'
export const FETCH_RECHARGES = 'FETCH_RECHARGES'
export const FETCH_RECHARGES_BY_ID = 'FETCH_RECHARGES_BY_ID'

export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS'
export const FETCH_TRANSACTIONS_BY_ID = 'FETCH_TRANSACTIONS_BY_ID'
