export const FETCH_PAYMENT_GATEWAY = "FETCH_PAYMENT_GATEWAY"
export const SET_PAYMENT_GATEWAY_LOADING = "SET_PAYMENT_GATEWAY_LOADING"
export const FETCH_PAYMENT_GATEWAY_BY_ID = "FETCH_PAYMENT_GATEWAY_BY_ID"
