export const FETCH_COMPANIES = 'FETCH_COMPANIES'
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS'
export const FETCH_COMPANIES_ERROR = 'FETCH_COMPANIES_ERROR'
export const SET_COMPANY_LOADING = 'SET_COMPANY_LOADING'
