export const SET_LOADING = "SET_LOADING"
export const FETCH_CASHBACKS = "FETCH_CASHBACKS"
export const FETCH_CASHBACK_BY_ID = "FETCH_CASHBACK_BY_ID"

// ===================== NEW ACTION =====================
export const SET_SIZE_PER_PAGE_CASHBACK = "SET_SIZE_PER_PAGE_CASHBACK"
export const SET_PAGE_CASHBACK = "SET_PAGE_CASHBACK"
export const SET_SEARCH_CASHBACK = "SET_SEARCH_CASHBACK"
export const SET_SORT_FIELD_CASHBACK = "SET_SORT_FIELD_CASHBACK"
export const SET_SORT_ORDER_CASHBACK = "SET_SORT_ORDER_CASHBACK"
