export const FETCH_SERVICES = 'FETCH_SERVICES'
export const FETCH_SERVICE_BY_ID = 'FETCH_SERVICE_BY_ID'
export const SET_LOADING = 'SET_LOADING'
export const FETCH_SERVICE_CATEGORIES = "FETCH_SERVICE_CATEGORIES"
